DROP DATABASE IF EXISTS DBNodeTS;
CREATE DATABASE IF NOT EXISTS DBNodeTS;
USE DBNodeTS;

CREATE TABLE IF NOT EXISTS comments (
    id INT AUTO_INCREMENT PRIMARY KEY ,
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at DATETIME,
    name VARCHAR(150) NOT NULL ,
    comment TEXT NOT NULL
);
